### ISSUE TITLE
add EVIOCGNAME to docs

### ISSUE THREAD

**Issue by samuelcolvin** [vpelletier/python-ioctl-opt#2]
Thanks a lot for this, it saved me from going mad.

It might be worth adding `EVIOCGNAME` to the readme, I spend ages trying to find a python implementation that was correct and opn happend upon your library by accident/luck.

```py
def EVIOCGNAME(length):
    return IOC(IOC_READ, ord('E'), 0x06, length)
```

**Comment by vpelletier** [comment]
> Thanks a lot for this, it saved me from going mad.

Happy my code could help !

> It might be worth adding `EVIOCGNAME` to the readme

Done in 9df466ba726038505bdf6f94e87609fa63d37110 . I must say I did not run the example on an correct device (so I could test it as far as "bad ioctl for device" error) for lack of immediate time. Code is inspired from [one of my other modules](https://github.com/vpelletier/python-hidraw/blob/1123a893425d78f799220cb55a4be5987e4f2e34/hidraw/__init__.py#L120) which uses this one. If you could check if it works it would be fantastic. Default length to 1024 is also a shot in the dark.

> I spend ages trying to find a python implementation that was correct and opn happend upon your library by accident/luck.

I could probably expand the keywords in `setup.py` to make this module easier to find. Ideas are welcome.

**Comment by samuelcolvin** [comment]
Thanks, closing as this is resolved for me.

My code https://github.com/samuelcolvin/mouse-events/blob/master/run.py#L47 seems to be working fine. 

It's only hack to run locally to read mouse events due to the horrors of gnome 3, so I'm not massively concerned about making sure it works in all corner cases.
